### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by faewihngs** [GlHhwa/GH-Stardew-Valley#3]
Hi, i was wondering if the peach body mod is going to get a 1.6 update? there are a couple of textures missing now that there is new items/actions

**Comment by GlHhwa** [comment]
Hello, I'm busy working overtime every day, so I'm updating it little by little on my day off. There are so many different types of pitch bodies that there is a lot of work, so please wait a little longer.

**Comment by GlHhwa** [comment]
> Hi, i was wondering if the peach body mod is going to get a 1.6 update? there are a couple of textures missing now that there is new items/actions

Hello, I'm busy working overtime every day, so I'm updating it little by little on my day off. There are so many different types of pitch bodies that there is a lot of work, so please wait a little longer.

**Comment by faewihngs** [comment]
I was absolutely okay waiting for it to get updated, i was unaware at the time if an update was going to happen. So happy that it got updated! Peach body is my go to body for my farmer
